Transform: 'AWS::Serverless-2016-10-31'
Resources:
  Covid19Lambda:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 256
      Timeout: 30
      CodeUri: ./
      Handler: lambda_function.my_handler
      Runtime: python3.7
