
Transform: 'AWS::Serverless-2016-10-31'
Resources:

  Covid19Lambda:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt  Covid19LambdaRole.Arn
      FunctionName: Covid19Lambda
      MemorySize: 512
      Timeout: 30
      CodeUri: ./
      Handler: lambda_function.my_handler
      Runtime: python3.7


  CovidRunTrigger:
    Type: AWS::Events::Rule
    Properties:
      Name: CovidRunTrigger
      Description: "Schedule run lambda"
      ScheduleExpression: "rate(1 day)"
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt Covid19Lambda.Arn
          Id: Covid19Lambda1

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref Covid19Lambda
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt CovidRunTrigger.Arn


  CovidBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "covid-19-plots"

  CovidBucketPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: CovidBucketPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - "s3:ListBucket"
            Effect: "Allow"
            Resource:
              - Fn::Join:
                  - ""
                  - - !GetAtt CovidBucket.Arn
                    - "/*"
          -
            Action:
              - "s3:PutObject"
            Effect: "Allow"
            Resource:
              - Fn::Join:
                  - ""
                  -
                    - !GetAtt CovidBucket.Arn
                    - "/*"

  Covid19LambdaRole:
    DependsOn:
      - CovidBucketPolicy
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: "/"
      ManagedPolicyArns:
        - !Ref CovidBucketPolicy
